baseURL: https://biehlerj.srht.site/
languageCode: en-us
title: Jacob Biehler
theme: PaperMod
pluralizeListTitles: "false"

params:
  env: production
  title: Jacob Biehler
  description: "Jacob Biehler's Personal Website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Jacob Biehler
  defaultTheme: dark
  profileMode:
    enabled: true
    subtitle: "Software Engineer and FOSS Enthusiast"
    imageUrl: "pfp.webp"
    imageTitle: "Jacob Biehler's profile picture"
    buttons:
      - name: Experience
        url: "/experience"
      - name: Projects
        url: "/projects"
      - name: Education
        url: "/education"
  socialIcons:
    - name: sourcehut
      url: "https://git.sr.ht/~biehlerj"
    - name: github
      url: "https://github.com/biehlerj"
    - name: gitlab
      url: "https://gitlab.com/biehlerj"
    - name: keybase
      url: "https://keybase.io/biehlerj"
    - name: linkedin
      url: "https://www.linkedin.com/in/jacob-biehler-475573139/"
    - name: email
      url: "jacob@biehlerj.xyz"

menu:
  main:
    - identifier: aboutme
      name: "About Me"
      url: "/about"
      weight: 7
    - identifier: experience
      name: Experience
      url: "/experience"
      weight: 8
    - identifier: projects
      name: Projects
      url: "/projects"
      weight: 9
    - identifier: education
      name: Education
      url: "/education"
      weight: 10
    - identifier: resume
      name: "Download my Resume"
      url: "resume.pdf"
      weight: 11